to_float_point_feat: ['StoreInventory', 'wasted_units', 'wasted_cost']
nan_features: ['sales_cost_x', 'sales_units', 'sales_value', 'wasted_units', 'wasted_cost', 'sales_cost_y']
numeric_features: ['StoreInventory', 'sales_cost_x', 'sales_value', 'price', 'cost', 'sales_cost_y']
cat_features: ['price_zone_&_class_name']
date_feature: 'date'
ts_by_features: ['class_name', 'item', 'store']
path_to_data: data/pd_milk_data.csv
path_to_save: data/

date_split: 2023-03-01
n_prev_days: 5