dataset:
  path_to_input: data/input/test_dataset.pt
  path_to_output: data/output/inf_CatEmbLSTM.csv
  batch_size: 64
  num_workers: 1
  lag: 14
  target: 'sales_units'

model:
  path: models/CatEmbLSTM.pt